### ISSUE TITLE
Pages Load Slowly

### ISSUE THREAD

**Issue by Zac-Zajdel** [shadcn-ui/taxonomy#173]
Hi everyone,

Starting to learn the app router and upgrade some side projects so I went to the 🐐 of UI components and found this sample. I pulled this down just to see how it was architected but I immediately noticed locally and even on the hosted website that switching between pages initially takes 3-4 seconds.

Is this the cost of server components 👀 or is there just something super unoptimized going on? I will continue to investigate and post here in the days ahead but compared to some of my next.js 12 apps, this performs much worse.

**Comment by vaynevayne** [comment]
same issue

**Comment by MenschenToaster** [comment]
In auth.ts: https://github.com/shadcn/taxonomy/blob/main/lib/auth.ts there is a database call in the jwt method. 

I've experimented with this before and in my own project this method gets called about 4–10 times per page load. Are you logged in? Because maybe that's the issue

**Comment by rajaryyn** [comment]
It's not the issue with server components. The issue came from webpack it's making hot reloading slow. Use turbo pack beta version

**Comment by S4ntiego** [comment]
It is the cost of server components in case of websites that utilize user authentication, at least in their current state, but it used to be much worse a few months ago, so let's hope that it will get even better over time.
