### ISSUE TITLE
null

### ISSUE THREAD

**Issue by JackRKelly** [shadcn-ui/taxonomy#177]

**Comment by Vlad-CSA** [comment]
I think the only reason - author prioritise different tasks. Do you have to work and configure everything when you set up this project? Definitely! Google + AI will help you. It's not Rocket science, everything is surmountable. If you feel you can help others and make such detailed instructions, go ahead, that's how open source works.

**Comment by JackRKelly** [comment]
> I think the only reason - author prioritise different tasks. Do you have to work and configure everything when you set up this project? Definitely! Google + AI will help you. It's not Rocket science, everything is surmountable. If you feel you can help others and make such detailed instructions, go ahead, that's how open source works.

Its definitely not rocket science! But I see some others struggling, so I think it could be useful
