### ISSUE TITLE
Allignment is not Correct

### ISSUE THREAD

**Issue by KirtiKamal** [shadcn-ui/taxonomy#181]
If we click on [Don't have an account? Sign Up](https://tx.shadcn.com/register) 

# The alignment is not correct , it is coming at the right extreme which is not good looking

<img width="960" alt="Screenshot 2023-07-18 095817" src="https://github.com/shadcn/taxonomy/assets/98299441/93764c1f-f604-41f2-9a66-abaa0c6bd493">

<img width="960" alt="Screenshot 2023-07-18 095727" src="https://github.com/shadcn/taxonomy/assets/98299441/b450182a-0148-4be6-a325-65d40e4bb4f5">

**Comment by KirtiKamal** [comment]
@shadcn how to run this project on the local system can you please help? I am unable to run this on my local system.

**Comment by prajapatdip** [comment]
Hey I wanna work on this issue but It's not running on my local environment can anyone help. I followed all the installation steps given in the README.md file.

**Comment by KirtiKamal** [comment]
same problem here . I am also unable to run it on my local machine
