### ISSUE TITLE
error contentlayer webpack

### ISSUE THREAD

**Issue by NicolasCassunde** [shadcn-ui/taxonomy#187]
`pnpm build

> taxonomy@0.2.0 build /Users/neo/Downloads/app.dominandocripto.com - cópia
> contentlayer build && next build

Generated 13 documents in .contentlayer
TypeError: The "code" argument must be of type number. Received an instance of Object
    at process.set [as exitCode] (node:internal/bootstrap/node:123:9)
    at Cli.runExit (/Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/clipanion@3.2.1_typanion@3.13.0/node_modules/clipanion/lib/advanced/Cli.js:232:26)
    at run (file:///Users/neo/Downloads/app.dominandocripto.com%20-%20co%CC%81pia/node_modules/.pnpm/@contentlayer+cli@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/cli/dist/index.js:26:5)
    at main (/Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/contentlayer@0.3.2_esbuild@0.18.17/node_modules/contentlayer/bin/cli.cjs:5:3) {
  code: 'ERR_INVALID_ARG_TYPE'
}
- info Loaded env from /Users/neo/Downloads/app.dominandocripto.com - cópia/.env.local
- info Loaded env from /Users/neo/Downloads/app.dominandocripto.com - cópia/.env
- warn You have enabled experimental feature (serverComponentsExternalPackages) in next.config.mjs.
- warn Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

Generated 13 documents in .contentlayer
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
- info Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${Date.now()}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown'
<w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown as file
<w>  at resolve esm file markdown-wasm/dist/markdown.node.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at resolve esm file ./markdown/markdown.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at resolve esm file @contentlayer/core
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at resolve esm file ./plugin.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at resolve esm file next-contentlayer
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at resolve commonjs /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
- info Creating an optimized production build .<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
- info Creating an optimized production build ..<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/getConfig/index.js for build dependencies failed at 'import(`file://${modulePath}?x=${Date.now()}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown'
<w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown as file
<w>  at resolve esm file markdown-wasm/dist/markdown.node.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at resolve esm file ./markdown/markdown.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at resolve esm file @contentlayer/core
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at resolve esm file ./plugin.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at resolve esm file next-contentlayer
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at resolve commonjs /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
- info Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Parsing of /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/dynamic-build.js for build dependencies failed at 'import(`file://${compiledConfigPath}`)'.
<w> Build dependencies behind this expression are ignored and might cause incorrect cache invalidation.
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'markdown-wasm/dist/markdown.node.js' in '/Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown'
<w> while resolving 'markdown-wasm/dist/markdown.node.js' in /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown as file
<w>  at resolve esm file markdown-wasm/dist/markdown.node.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/markdown/markdown.js
<w>  at resolve esm file ./markdown/markdown.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/@contentlayer+core@0.3.2_esbuild@0.18.17/node_modules/@contentlayer/core/dist/index.js
<w>  at resolve esm file @contentlayer/core
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/plugin.js
<w>  at resolve esm file ./plugin.js
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/node_modules/.pnpm/next-contentlayer@0.3.2_esbuild@0.18.17_next@13.4.1_react-dom@18.2.0_react@18.2.0/node_modules/next-contentlayer/dist/index.js
<w>  at resolve esm file next-contentlayer
<w>  at file dependencies /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at file /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs
<w>  at resolve commonjs /Users/neo/Downloads/app.dominandocripto.com - cópia/next.config.mjs`

my package.json:

`"scripts": {
    "dev": "concurrently \"contentlayer dev\" \"next dev\"",
    "build": "contentlayer build && next build",
    "turbo": "next dev --turbo",
    "start": "next start",
    "lint": "next lint",
    "preview": "next build && next start",
    "postinstall": "prisma generate"
  },
  "dependencies": {
    "@editorjs/code": "^2.8.0",
    "@editorjs/editorjs": "^2.26.5",
    "@editorjs/embed": "^2.5.3",
    "@editorjs/header": "^2.7.0",
    "@editorjs/inline-code": "^1.4.0",
    "@editorjs/link": "^2.5.0",
    "@editorjs/list": "^1.8.0",
    "@editorjs/paragraph": "^2.9.0",
    "@editorjs/table": "^2.2.1",
    "@hookform/resolvers": "^3.1.0",
    "@next-auth/prisma-adapter": "^1.0.6",
    "@prisma/client": "^4.13.0",
    "@radix-ui/react-accessible-icon": "^1.0.2",
    "@radix-ui/react-accordion": "^1.1.1",
    "@radix-ui/react-alert-dialog": "^1.0.3",
    "@radix-ui/react-aspect-ratio": "^1.0.2",
    "@radix-ui/react-avatar": "^1.0.2",
    "@radix-ui/react-checkbox": "^1.0.3",
    "@radix-ui/react-collapsible": "^1.0.2",
    "@radix-ui/react-context-menu": "^2.1.3",
    "@radix-ui/react-dialog": "^1.0.3",
    "@radix-ui/react-dropdown-menu": "^2.0.4",
    "@radix-ui/react-hover-card": "^1.0.5",
    "@radix-ui/react-label": "^2.0.1",
    "@radix-ui/react-menubar": "^1.0.2",
    "@radix-ui/react-navigation-menu": "^1.1.2",
    "@radix-ui/react-popover": "^1.0.5",
    "@radix-ui/react-progress": "^1.0.2",
    "@radix-ui/react-radio-group": "^1.1.2",
    "@radix-ui/react-scroll-area": "^1.0.3",
    "@radix-ui/react-select": "^1.2.1",
    "@radix-ui/react-separator": "^1.0.2",
    "@radix-ui/react-slider": "^1.1.1",
    "@radix-ui/react-slot": "^1.0.1",
    "@radix-ui/react-switch": "^1.0.2",
    "@radix-ui/react-tabs": "^1.0.3",
    "@radix-ui/react-toast": "^1.1.3",
    "@radix-ui/react-toggle": "^1.0.2",
    "@radix-ui/react-toggle-group": "^1.0.3",
    "@radix-ui/react-tooltip": "^1.0.5",
    "@t3-oss/env-nextjs": "^0.2.2",
    "@typescript-eslint/parser": "^5.59.0",
    "@vercel/analytics": "^1.0.0",
    "@vercel/og": "^0.0.21",
    "class-variance-authority": "^0.4.0",
    "clsx": "^1.2.1",
    "cmdk": "^0.1.22",
    "concurrently": "^8.0.1",
    "contentlayer": "^0.3.2",
    "date-fns": "^2.29.3",
    "lucide-react": "^0.92.0",
    "next": "13.4.1",
    "next-auth": "4.22.1",
    "next-contentlayer": "^0.3.2",
    "next-themes": "^0.2.1",
    "nodemailer": "^6.9.1",
    "postmark": "^3.0.15",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-day-picker": "^8.7.1",
    "react-dom": "^18.2.0",
    "react-editor-js": "^2.1.0",
    "react-hook-form": "^7.43.9",
    "react-textarea-autosize": "^8.4.1",
    "sharp": "^0.31.3",
    "shiki": "^0.11.1",
    "stripe": "^11.18.0",
    "tailwind-merge": "^1.12.0",
    "tailwindcss-animate": "^1.0.5",
    "zod": "^3.21.4"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.6.1",
    "@commitlint/config-conventional": "^17.6.1",
    "@ianvs/prettier-plugin-sort-imports": "^3.7.2",
    "@tailwindcss/line-clamp": "^0.4.4",
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "^18.16.0",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
    "autoprefixer": "^10.4.14",
    "eslint": "^8.39.0",
    "eslint-config-next": "13.3.1",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-tailwindcss": "^3.11.0",
    "husky": "^8.0.3",
    "mdast-util-toc": "^6.1.1",
    "postcss": "^8.4.23",
    "prettier": "^2.8.8",
    "prettier-plugin-tailwindcss": "^0.1.13",
    "pretty-quick": "^3.1.3",
    "prisma": "^4.13.0",
    "rehype": "^12.0.1",
    "rehype-autolink-headings": "^6.1.1",
    "rehype-pretty-code": "^0.9.5",
    "rehype-slug": "^5.1.0",
    "remark": "^14.0.2",
    "remark-gfm": "^3.0.1",
    "tailwindcss": "^3.3.1",
    "typescript": "4.7.4",
    "unist-util-visit": "^4.1.2"
  }
}`

**Comment by dlin-me** [comment]
+1

**Comment by tyrozz** [comment]
Do you use node 20? Give it a try with node 18. I downgraded to node18 and the error went away. (With "next": "14.0.1", "next-contentlayer": "^0.3.4", "contentlayer": "^0.3.4")

**Comment by alexandrosk** [comment]
i have the same error with node 18 and 20 :/

**Comment by Kickbykick** [comment]
I have the same error too, I amusing `node v20.10.0` with `"next": "14.0.1", "next-contentlayer": "^0.3.4", "contentlayer": "^0.3.4"`

**Comment by Kickbykick** [comment]
I uninstalled `node v20.10.0` and installed `node v18.17.1` here https://nodejs.org/en/blog/release/v18.17.1.

It worked
