### ISSUE TITLE
[Bug]  Login button still visible on home page after user logs in

### ISSUE THREAD

**Issue by Roshan-Nayak1** [shadcn-ui/taxonomy#194]
I have noticed that the login button is still visible on the home page even after I have logged in to the website. This issue is causing confusion and may lead to users accidentally logging out. I have tried refreshing the page and clearing my cache, but the issue persists.

Steps to reproduce:
Go to the website and click on the login button.
Enter your login credentials and click on the login button.
After logging in, observe that the login button is still visible on the home page.

Expected behavior:
After logging in, the login button should disappear and be replaced by a logout button on the home page.

Actual behavior:
The login button is still visible on the home page even after logging in.

Screenshot: After Login
![Screenshot 2023-08-04 005213](https://github.com/shadcn-ui/taxonomy/assets/90680393/6ce98d2c-9778-46f7-b510-8001198d3796)

Thank you for your attention to this matter.

**Comment by DevBlogs404** [comment]
hey @Roshan-Nayak1 , is this issue still open?

**Comment by HujefP** [comment]
I would like to take this task

**Comment by Roshan-Nayak1** [comment]
> hey @Roshan-Nayak1 , is this issue still open?

Issue solved , still not updated on taxonomy official website.
