### ISSUE TITLE
Login page Server error

### ISSUE THREAD

**Issue by enej-g** [shadcn-ui/taxonomy#231]
Hello,
When I click on the Login button, I get the following error: Server error
There is a problem with the server configuration.

Check the server logs for more information.

In my logs, there's the following error: [next-auth][error][NO_SECRET] 
https://next-auth.js.org/errors#no_secret,

Even through I specified it in the .env file:
NEXTAUTH_SECRET=a299eaexxxxxxxxxxxxxxxxxx88f7783

**Comment by Lunatic83** [comment]
If you are experiencing it on vercel you have to setup the environment variable and redeploy it. 
If you are experiencing it on your local environment you have to restart the server.

**Comment by enej-g** [comment]
Worked, thanks, have a nice day/evening!
