### ISSUE TITLE
The toast's close button is colliding with the edge of its container.

### ISSUE THREAD

**Issue by Irtiza751** [shadcn-ui/taxonomy#268]
### The toast's close button is colliding with the edge of its container.

![image](https://github.com/shadcn-ui/taxonomy/assets/91867702/1c00fa5a-cc65-4a63-8145-d575d2e04d7f)

**Comment by shreyashChitkula** [comment]
can i solve this issue

**Comment by Irtiza751** [comment]
Sure, go for it.
