### ISSUE TITLE
Content Layer page does not exist

### ISSUE THREAD

**Issue by alieldeba** [shadcn-ui/taxonomy#290]
When I tried to see what is in the link it gives me 404, so this is a broken link that need to be fixed 🙂
and also I see that 404 page does not have any UI

![image](https://github.com/shadcn-ui/taxonomy/assets/88302640/c1233708-b12d-43d9-ab5a-41a6f3084d72)

![image](https://github.com/shadcn-ui/taxonomy/assets/88302640/889eabdf-39c2-4654-a784-804bff467ead)

Links:
https://tx.shadcn.com/docs
https://tx.shadcn.com/docs/documentation/contentlayer

**Comment by Satyansh-07** [comment]
Hi @alieldeba , I don't think this is an issue, the creator is trying to create a new page with (/docs/documentation/contentlayer) instead of redirecting the user to contentLayers.dev. Please correct me if I am wrong. I found the cause though.

**Comment by alieldeba** [comment]
> Hi @alieldeba , I don't think this is an issue, the creator is trying to create a new page with (/docs/documentation/contentlayer)which he has still not created as repo itself mentions that work is still in progress instead of redirecting the user to (contentlayers.dev.) Please correct me if I am wrong. I found the cause though.

oh if that is the case it is ok I thought that content layer page were deleted and he forgot to remove its links
