### ISSUE TITLE
Profile icon not showing on the home page after successful login

### ISSUE THREAD

**Issue by ashrafchowdury** [shadcn-ui/taxonomy#89]
In the application, after a user successfully logs in, the site is supposed to show the user's profile icon on the home page. However, instead of showing the profile icon, the login button is still displayed.

## Expected Result:
Profile icon not showing on the home page after successful login.

![image](https://user-images.githubusercontent.com/87828904/231695817-c92b7360-77df-476e-a93e-4ca3652fd976.png)

## Actual Result
After successful login, the login button is still being displayed on the home page.

![image](https://user-images.githubusercontent.com/87828904/231695919-1fd9fe19-55b8-4b7c-ba2f-7fa10c74ff7e.png)

### Preview

https://user-images.githubusercontent.com/87828904/231696429-8d30052f-cade-4b4a-965d-ddf8f04145ea.mp4

**Comment by Natchii59** [comment]
He just didn't add it.
https://github.com/shadcn/taxonomy/blob/main/app/(marketing)/layout.tsx#L21-L31

**Comment by chandra1899** [comment]
is this issue still open , can i work on this
